const { chromium, expect } = require('@playwright/test')
;(async () => {
 const browser = await chromium.launch({ headless: true })
 try {
  const page = await browser.newPage()
  await page.route('**/configuracion/empresas/18', r => r.fulfill({ json: {success:true,data:{id:18,ruc:'20222222222',razon_social:'Empresa prueba'}} }))
  await page.route('**/percepciones/catalogos', r => r.fulfill({ json: {success:true,data:{regimenesPercepcion:[{id:1,nombre:'Régimen de prueba',descripcion:'01'}]}} }))
  await page.route('**/retenciones/catalogos', r => r.fulfill({ json: {success:true,data:{regimenesRetencion:[{id:2,nombre:'Régimen de prueba',descripcion:'01'}]}} }))
  await page.goto('http://127.0.0.1:5177/test/tributo-origen-harness.html')
  for (const [label, key, tasa, monto] of [['Percepción','percepcion','2','2.00'],['Retención','retencion','3','3.00']]) {
   const section = page.getByRole('region', {name:label,exact:true})
   await section.getByRole('checkbox').check()
   await expect(section).toContainText('Empresa prueba')
   await section.getByLabel('Régimen',{exact:true}).selectOption('01')
   await section.getByLabel('Tasa (%)',{exact:true}).fill(tasa)
   await expect(section).toContainText(`S/ ${monto}`)
   const data = await page.evaluate(key=>window.testState[key],key)
   expect(data.idEmpresa).toBe(18)
   expect(data.baseImponible).toBe(100)
   expect(data.regimen).toBe('01')
  }
  const retencion = page.getByRole('region',{name:'Retención',exact:true})
  await expect(retencion).toContainText('neto de retención: S/ 97.00')
  const percepcion = page.getByRole('region',{name:'Percepción',exact:true})
  await expect(percepcion).toContainText('con percepción: S/ 102.00')
  await page.evaluate(()=>window.testState.total=200)
  await expect(percepcion.getByLabel('Base de la operación (S/)',{exact:true})).toHaveValue('200')
  await percepcion.getByLabel('Base de la operación (S/)',{exact:true}).fill('201')
  await expect(percepcion.getByRole('alert')).toContainText('no superar')
  await percepcion.getByRole('checkbox').uncheck()
  expect(await page.evaluate(()=>window.testState.percepcion)).toBeUndefined()
  console.log('OK: secciones opcionales, empresa, régimen, importes, cambio de total, validación y desactivación')
 } finally { await browser.close() }
})().catch(e=>{console.error(e);process.exitCode=1})
