import { PermisoBanderas } from '@/shared/constants/permissions'
import type { TipoTributo, TributoConfig } from '../interfaces/tributo.interface'

export const TRIBUTOS_CONFIG: Record<TipoTributo, TributoConfig> = {
  percepcion: {
    tipo: 'percepcion',
    api: '/percepciones',
    singular: 'Percepción',
    plural: 'Percepciones',
    contraparte: 'Cliente',
    origenSingular: 'comprobante de venta',
    origenPlural: 'comprobantes de venta',
    operacion: 'cobro',
    serieEjemplo: 'P001',
    seriePrefijo: 'P',
    rutas: { lista: 'admin-percepciones', nueva: 'admin-percepciones-nueva', detalle: 'admin-percepciones-detalle' },
    paths: { lista: '/admin/ventas/percepciones', nueva: '/admin/ventas/percepciones/nueva' },
    permisos: {
      listar: PermisoBanderas.PERCEPCIONES_LISTAR,
      ver: PermisoBanderas.PERCEPCIONES_VER,
      crear: PermisoBanderas.PERCEPCIONES_CREAR,
      emitir: PermisoBanderas.PERCEPCIONES_EMITIR,
    },
    campos: {
      idContraparte: 'id_cliente',
      nombreContraparte: 'nombre_cliente',
      documentoContraparte: 'documento_cliente',
      montoTributo: 'monto_percibido',
      montoNeto: 'monto_cobrado',
      detalleTributo: 'imp_percibido',
      detalleNeto: 'imp_cobrar',
      detalleFecha: 'fecha_percepcion',
      catalogoRegimenes: 'regimenesPercepcion',
      filtroContraparte: 'idCliente',
    },
    breadcrumbPadre: { label: 'Ventas', to: '/admin/ventas/comprobantes' },
    soloProveedores: false,
  },
  retencion: {
    tipo: 'retencion',
    api: '/retenciones',
    singular: 'Retención',
    plural: 'Retenciones',
    contraparte: 'Proveedor',
    origenSingular: 'compra',
    origenPlural: 'compras',
    operacion: 'pago',
    serieEjemplo: 'R001',
    seriePrefijo: 'R',
    rutas: { lista: 'admin-retenciones', nueva: 'admin-retenciones-nueva', detalle: 'admin-retenciones-detalle' },
    paths: { lista: '/admin/compras/retenciones', nueva: '/admin/compras/retenciones/nueva' },
    permisos: {
      listar: PermisoBanderas.RETENCIONES_LISTAR,
      ver: PermisoBanderas.RETENCIONES_VER,
      crear: PermisoBanderas.RETENCIONES_CREAR,
      emitir: PermisoBanderas.RETENCIONES_EMITIR,
    },
    campos: {
      idContraparte: 'id_proveedor',
      nombreContraparte: 'nombre_proveedor',
      documentoContraparte: 'documento_proveedor',
      montoTributo: 'monto_retenido',
      montoNeto: 'monto_pagado',
      detalleTributo: 'imp_retenido',
      detalleNeto: 'imp_pagar',
      detalleFecha: 'fecha_retencion',
      catalogoRegimenes: 'regimenesRetencion',
      filtroContraparte: 'idProveedor',
    },
    breadcrumbPadre: { label: 'Compras', to: '/admin/compras' },
    soloProveedores: true,
  },
}
